name: Dependabot Auto-approve

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  auto-approve:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    env:
      GH_TOKEN: ${{ github.token }}
      PR_URL: ${{ github.event.pull_request.html_url }}

    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Fetch Dependabot PR metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Approve Dependabot PR
        run: |
          gh pr checkout "$PR_URL"
          if [ \
            "$(gh pr status \
              --json reviewDecision \
              -q .currentBranch.reviewDecision)" \
            != "APPROVED" \
          ]; then
            gh pr review --approve "$PR_URL"
          else
            echo "PR already approved."
          fi

      - name: Enable auto-merge on Dependabot PR
        run: gh pr merge --auto --merge "$PR_URL"
